name: 'My Workflow'

on:
  push:
    branch: [master]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1
        with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.MY_TOKEN_SECRET }}
        NETLIFY_DEPLOY_TO_PROD: true
